rem ::LO0_Introduction
pandoc -S "./LO0_Introduction/documents/01_Introduction.docx" -M docPath="./LO0_Introduction/documents/01_Introduction.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO0_Introduction/01_Introduction.md" & node update_md.js "./LO0_Introduction/01_Introduction.md"

rem ::LO1_Analyze_a_Transaction
pandoc -S "./LO1_Analyze_a_Transaction/documents/01_Introduction.docx" -M docPath="./LO1_Analyze_a_Transaction/documents/01_Introduction.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO1_Analyze_a_Transaction/01_Introduction.md" & node update_md.js "./LO1_Analyze_a_Transaction/01_Introduction.md"

pandoc -S "./LO1_Analyze_a_Transaction/documents/02_Transaction_Issue_Stock_to_Stockholders.docx" -M docPath="./LO1_Analyze_a_Transaction/documents/02_Transaction_Issue_Stock_to_Stockholders.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO1_Analyze_a_Transaction/02_Transaction_Issue_Stock_to_Stockholders.md" & node update_md.js "./LO1_Analyze_a_Transaction/02_Transaction_Issue_Stock_to_Stockholders.md"

pandoc -S "./LO1_Analyze_a_Transaction/documents/03_Transaction_Obtain_Loan_from_Bank.docx" -M docPath="./LO1_Analyze_a_Transaction/documents/03_Transaction_Obtain_Loan_from_Bank.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO1_Analyze_a_Transaction/03_Transaction_Obtain_Loan_from_Bank.md" & node update_md.js "./LO1_Analyze_a_Transaction/03_Transaction_Obtain_Loan_from_Bank.md"

pandoc -S "./LO1_Analyze_a_Transaction/documents/04_Transaction_Purchase_Equipment_with_Cash.docx" -M docPath="./LO1_Analyze_a_Transaction/documents/04_Transaction_Purchase_Equipment_with_Cash.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO1_Analyze_a_Transaction/04_Transaction_Purchase_Equipment_with_Cash.md" & node update_md.js "./LO1_Analyze_a_Transaction/04_Transaction_Purchase_Equipment_with_Cash.md"

pandoc -S "./LO1_Analyze_a_Transaction/documents/05_Transaction_Development_of_a_Company_Logo_with_Cash.docx" -M docPath="./LO1_Analyze_a_Transaction/documents/05_Transaction_Development_of_a_Company_Logo_with_Cash.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO1_Analyze_a_Transaction/05_Transaction_Development_of_a_Company_Logo_with_Cash.md" & node update_md.js "./LO1_Analyze_a_Transaction/05_Transaction_Development_of_a_Company_Logo_with_Cash.md"

pandoc -S "./LO1_Analyze_a_Transaction/documents/06_Transaction_Purchase_Furniture_on_Account.docx" -M docPath="./LO1_Analyze_a_Transaction/documents/06_Transaction_Purchase_Furniture_on_Account.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO1_Analyze_a_Transaction/06_Transaction_Purchase_Furniture_on_Account.md" & node update_md.js "./LO1_Analyze_a_Transaction/06_Transaction_Purchase_Furniture_on_Account.md"

pandoc -S "./LO1_Analyze_a_Transaction/documents/07_Assessment.docx" -M docPath="./LO1_Analyze_a_Transaction/documents/07_Assessment.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO1_Analyze_a_Transaction/07_Assessment.md" & node update_md.js "./LO1_Analyze_a_Transaction/07_Assessment.md"

rem ::LO2_Prepare_a_Classified_Balance_Sheet
pandoc -S "./LO2_Prepare_a_Classified_Balance_Sheet/documents/01_Introduction.docx" -M docPath="./LO2_Prepare_a_Classified_Balance_Sheet/documents/01_Introduction.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO2_Prepare_a_Classified_Balance_Sheet/01_Introduction.md" & node update_md.js "./LO2_Prepare_a_Classified_Balance_Sheet/01_Introduction.md"

rem ::LO3_Evaluate_a_Companys_Ability_to_Pay_Its_Short_Term_Debt
pandoc -S "./LO3_Evaluate_a_Companys_Ability_to_Pay_Its_Short_Term_Debt/documents/01_Introduction.docx" -M docPath="./LO3_Evaluate_a_Companys_Ability_to_Pay_Its_Short_Term_Debt/documents/01_Introduction.docx" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "./LO3_Evaluate_a_Companys_Ability_to_Pay_Its_Short_Term_Debt/01_Introduction.md" & node update_md.js "./LO3_Evaluate_a_Companys_Ability_to_Pay_Its_Short_Term_Debt/01_Introduction.md"